---


# Configure nginx to serve django application


- name: Create nginx configuration file for django app

  template: src=../templates/django_nginx_conf 
      dest=/etc/nginx/sites-available/{{ app_name }}

  notify:
    - Create symlink for django app nginx configuration file


- name: Create symlink for django app nginx configuration file

  ignore_errors: yes

  command: ln -s /etc/nginx/sites-available/{{ app_name }}
      /etc/nginx/sites-enabled/{{ app_name}}


- name: Create app logs directory

  ignore_errors: yes

  file: path=/var/log/nginx/{{ app_name }} state=directory


- name: Touch log files

  file: path=/var/log/nginx/{{ app_name }}/access.log state=touch

  file: path=/var/log/nginx/{{ app_name }}/error.log state=touch


- name: Restart nginx

  service: name=nginx state=restarted 

